### ISSUE TITLE
Checkout express: Crash capturing the sum authorized

### ISSUE THREAD

**Issue by gine** [angelleye/paypal-woocommerce#1531]
php: 7.4
Wordpress: 2.6.2
Woocommerce: 5.0.0
Plugin version: 2.5.1

Trying to capture the entire sum with checkout express  i catch this error on my log. I updated my e-commerce today from an old woocommerce 3.9.1 and then this problem is appeared. The capture action is completed but on wordpress i get the error page.

```
[22-Feb-2021 17:49:19 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get_id() on bool in /srv/data/web/vhosts/1ebded1786c44cec96163117539edc40.testmyurl.ws/htdocs/wp-content/plugins/paypal-woocommerce-2.5.1/angelleye-includes/angelleye-utility.php:153
Stack trace:
#0 /srv/data/web/vhosts/1ebded1786c44cec96163117539edc40.testmyurl.ws/htdocs/wp-content/plugins/paypal-woocommerce-2.5.1/angelleye-includes/angelleye-utility.php(1325): AngellEYE_Utility->angelleye_woocommerce_order_actions()
#1 /srv/data/web/vhosts/1ebded1786c44cec96163117539edc40.testmyurl.ws/htdocs/wp-content/plugins/paypal-woocommerce-2.5.1/angelleye-includes/angelleye-utility.php(466): AngellEYE_Utility->angelleye_paypal_for_woocommerce_order_status_handler()
#2 /srv/data/web/vhosts/1ebded1786c44cec96163117539edc40.testmyurl.ws/htdocs/wp-content/plugins/paypal-woocommerce-2.5.1/angelleye-includes/angelleye-utility.php(390): AngellEYE_Utility->pfw_do_capture()
#3 /srv/data/web/vhosts/1ebded1786c44cec96163117539edc40.testmyurl.ws/htdocs/wp-includes/class-wp-hook.php(287):  in /srv/data/web/vhosts/1ebded1786c44cec96163117539edc40.testmyurl.ws/htdocs/wp-content/plugins/paypal-woocommerce-2.5.1/angelleye-includes/angelleye-utility.php on line 153
```

**Comment by drewangell** [comment]
@gine Thanks for the report.  We're on it, and we'll get back to you ASAP!

**Comment by gine** [comment]
Now i have opened a ticket on your help desk: AHD-13316

**Comment by gine** [comment]
After the last update(wordpress + woocommerce) the problem seems to be solved. 
I can confirm to you tomorrow when my customer contact me.

**Comment by gine** [comment]
Whit last software version everything works well

**Comment by drewangell** [comment]
@gine Thanks again for your feedback and verification that it's resolved.  Much appreciated!
