### ISSUE TITLE
Plugins conflict woocommerce_sagepaycw woocommerce-gateway-stripe

### ISSUE THREAD

**Issue by stefopl** [angelleye/paypal-woocommerce#1941]
The call to `should_show_payment_request_button` at line

```php
wp-content/plugins/paypal-for-woocommerce/ppcp-gateway/class-angelleye-paypal-ppcp-smart-button.php:1733
```

```php
if ($payment_request_configuration->should_show_payment_request_button()) {
```

causes all calls like `is_page()`, `is_cart()`, `is_singular()` to trigger a notice:

```
Notice: Function is_page was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false. Please see Debugging in WordPress for more information. (This message was added in version 3.1.0.) in /wp-includes/functions.php on line 5905
```

and the usage of the `woocommerce_sagepaycw.php` plugin becomes completely impossible because of:

```
Fatal error: Uncaught Error: Call to a member function wp_rewrite_rules() on null in /wp-includes/rewrite.php:564 Stack trace: #0 /wp-content/plugins/woocommerce_sagepaycw/woocommerce_sagepaycw.php(714): url_to_postid() #1 /wp-content/plugins/woocommerce_sagepaycw/woocommerce_sagepaycw.php(599): woocommerce_sagepaycw_get_page_id() #2 /wp-content/plugins/woocommerce_sagepaycw/woocommerce_sagepaycw.php(535): woocommerce_sagepaycw_is_plugin_page() #3 /wp-includes/class-wp-hook.php(310): woocommerce_sagepaycw_is_checkout() #4 /wp-includes/plugin.php(205): WP_Hook->apply_filters() #5 /wp-content/plugins/woocommerce/includes/wc-conditional-functions.php(112): apply_filters() #6 /wp-content/plugins/woocommerce-gateway-stri in /wp-includes/rewrite.php on line 564
```

WP Core Version: 6.3.2

Plugins:

clearpay-gateway-for-woocommerce 3.6.1
**paypal-for-woocommerce 4.3.2**
woocommerce 8.2.1
**woocommerce_sagepaycw 5.0.89**
**woocommerce-gateway-stripe 7.6.1**

**Comment by devchristina2** [comment]
Hi @stefopl, 

I'm sorry for not getting back to you sooner. Our support processes have changed, and the issues here have not been addressed. I created a bug ticket, PFW-1900, and assigned it to our engineers in our upcoming sprint. I'll close this issue for now; please reply to this issue if you have further questions. 

Thanks, Christina.
