### ISSUE TITLE
AutoShip Compatibility Bug..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#718]
* https://mail.google.com/mail/u/0/#inbox/15ba226c67fe0ba0

>Testing 1.4.3 on our staging server... still getting an error unfortunately. :( Pages like the main Coupons admin, among others, load blank (just the left menu). When I enable WP_DEBUG, I get this error:

>Fatal error: Uncaught Error: Call to a member function get_id() on boolean in /nas/content/staging/cannapet2016/wp-content/plugins/paypal-for-woocommerce/angelleye-includes/angelleye-utility.php:637 Stack trace: #0 [internal function]: AngellEYE_Utility->angelleye_woocommerce_payment_gateway_supports(true, 'tokenization', Object(WC_Gateway_PayPal_Express_AngellEYE)) #1 /nas/content/staging/cannapet2016/wp-includes/class-wp-hook.php(298): call_user_func_array(Array, Array) #2 /nas/content/staging/cannapet2016/wp-includes/plugin.php(203): WP_Hook->apply_filters(true, Array) #3 /nas/content/staging/cannapet2016/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-payment-gateway.php(359): apply_filters('woocommerce_pay...', true, 'tokenization', Object(WC_Gateway_PayPal_Express_AngellEYE)) #4 /nas/content/staging/cannapet2016/wp-content/plugins/woocommerce-autoship/src/admin.php(342): WC_Payment_Gateway->supports('tokenization') #5 /nas/content/staging/cannapet2016/wp-content/plugins/woocommerce-autoship/src/admin.p in /nas/content/staging/cannapet2016/wp-content/plugins/paypal-for-woocommerce/angelleye-includes/angelleye-utility.php on line 637

>And just to clarify... when I deactivate either your plugin, or Autoship, things work again (no errors). Something about the combination is causing issues. :-/

**Comment by angelleye** [comment]
[woocommerce-autoship-4.1.5.zip](https://github.com/angelleye/paypal-woocommerce/files/994972/woocommerce-autoship-4.1.5.zip)
