### ISSUE TITLE
PHP Fatal Error - Uncaught Error - get_base_country()..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#887]
* https://mail.google.com/mail/u/0/#inbox/15ec46bd91eee97d

>Fatal error: Uncaught Error: Call to a member function get_base_country() on null in /home/buildaco/public_html/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php:84 Stack trace: #0 /home/buildaco/public_html/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(67): WC_Payment_Gateways->init() #1 /home/buildaco/public_html/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(40): WC_Payment_Gateways->__construct() #2 /home/buildaco/public_html/wp-includes/class-wp-hook.php(298): WC_Payment_Gateways::instance('wc_gateway_payp...') #3 /home/buildaco/public_html/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array) #4 /home/buildaco/public_html/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #5 /home/buildaco/public_html/wp-content/plugins/woocommerce/includes/class-wc-api.php(90): do_action('woocommerce_api...', 'wc_gateway_payp...') #6 /home/buildaco/public_html/wp-includes/class-wp-hook.php(298): WC_API->handle_api_requests(Object(WP)) #7 /home/bu in /home/buildaco/public_html/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php on line 84

User reports this is happening on two of his sites: one running PHP 7.0 and the other running PHP 5.6.

**Comment by angelleye** [comment]
Customer disabled other plugins and found that the WordPress 2-Step Verification plugin caused this error.
